version: "3.8"

services:
  obs-rtmp:
    build: .
    container_name: obs-rtmp
    env_file: .env
    ports:
      - "${RTMP_PORT}:1935"
      - "${HTTP_PORT}:8081"
    volumes:
      - ${RECORD_PATH}:/recordings
    restart: unless-stopped