version: "3.8"

services:
  obs-rtmp:
    build: .
    container_name: obs-rtmp
    env_file: .env
    ports:
      - "${RTMP_PORT}:${RTMP_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - ${RECORD_PATH}:/recordings
    restart: unless-stopped