version: "3.8"

services:
  obs-rtmp:
    image: alfg/nginx-rtmp:latest
    container_name: obs-rtmp
    restart: unless-stopped

    # Подгружаем .env внутрь контейнера
    env_file:
      - .env

    # Пробрасываем порты
    ports:
      - "${RTMP_PORT}:${RTMP_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"

    # Монтируем конфиг и каталог для записей
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ${RECORD_PATH}:/recordings

    # Включаем модуль rtmp
    command: >
      /bin/sh -c "
      apk add --no-cache nginx-mod-rtmp &&
      nginx -g 'daemon off;'
      "